name: 'nightly artifacts cleanup'
on: [push]
  #schedule:
   #- cron: '* * * * *' # every night at 0 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'
